# Site settings
title: "~"
name: Srinivasan Raguraman
email: email@sragu.com
description: developer, technologist

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sragu.xyz" # the base hostname & protocol for your site

twitter_username: sragu
github_username:  sragu
keybase_username:  sragu

# Build settings
markdown: kramdown

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
  - jekyll-feed
  - jekyll-press # not supported by github-pages so you need to push manually
