# Site settings
title: sragu.xyz
email: email@sragu.xyz
description: >
  All things about me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sragu.xyz" # the base hostname & protocol for your site
twitter_username: sragu
github_username:  sragu

# Build settings
markdown: kramdown
