# Site settings
title: type blog
email: email@sragu.xyz
description: > # this means to ignore newlines until "baseurl:"
  This site is maintained by Srinivasan Raguraman.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sragu.xyz" # the base hostname & protocol for your site
twitter_username: sragu
github_username:  sragu

# Build settings
markdown: kramdown
